namespace: default
image:
  - name: springcommunity/spring-petclinic-config-server
    portExpose: 8888
  - name: springcommunity/spring-petclinic-discovery-server
    portExpose: 8761
  - name: springcommunity/spring-petclinic-customers-service
    portExpose: 8081
  - name: springcommunity/spring-petclinic-visits-service
    portExpose: 8082
  - name: springcommunity/spring-petclinic-vets-service
    portExpose: 8083
  - name: springcommunity/spring-petclinic-api-gateway
    portExpose: 8080
  - name: openzipkin/zipkin
    portExpose: 9411
  - name: springcommunity/spring-petclinic-admin-server
    portExpose: 9090
nodePort:
  - 31235
  - 31121
  - 31436
  - 30899
  - 30543
  - 32057
  - 31849
  - 30037
appName:
  - config-server
  - discovery-server
  - customers-service
  - visits-service
  - vets-service
  - api-gateway
  - tracing-server
  - admin-server
cantReplicas:
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
  - 1
autoscaling: true
minReplicas: 1
maxReplicas: 5
targetCPUUtilizationPercentage: 80