namespace: default
image:
  - name: springcommunity/spring-petclinic-config-server
    portExpose: 8888
  - name: springcommunity/spring-petclinic-discovery-server
    portExpose: 8761
  - name: springcommunity/spring-petclinic-customers-service
    portExpose: 8081
  - name: springcommunity/spring-petclinic-visits-service
    portExpose: 8082
  - name: springcommunity/spring-petclinic-vets-service
    portExpose: 8083
  - name: springcommunity/spring-petclinic-api-gateway
    portExpose: 8080
  - name: openzipkin/zipkin
    portExpose: 9411
  - name: springcommunity/spring-petclinic-admin-server
    portExpose: 9090
nodePort:
  - 32680
  - 30616
  - 31323
  - 32131
  - 32144
  - 32247
  - 31816
  - 32497
appName:
  - config-server
  - discovery-server
  - customers-service
  - visits-service
  - vets-service
  - api-gateway
  - tracing-server
  - admin-server
cantReplicas:
  - 2
  - 0
  - 1
  - 0
  - 0
  - 0
  - 0
  - 0
autoscaling: true
minReplicas: 1
maxReplicas: 5
targetCPUUtilizationPercentage: 80