namespace: default
image:
  - name: springcommunity/spring-petclinic-config-server
    portExpose: 8888
  - name: springcommunity/spring-petclinic-discovery-server
    portExpose: 8761
  - name: springcommunity/spring-petclinic-customers-service
    portExpose: 8081
  - name: springcommunity/spring-petclinic-visits-service
    portExpose: 8082
  - name: springcommunity/spring-petclinic-vets-service
    portExpose: 8083
  - name: springcommunity/spring-petclinic-api-gateway
    portExpose: 8080
  - name: openzipkin/zipkin
    portExpose: 9411
  - name: springcommunity/spring-petclinic-admin-server
    portExpose: 9090
nodePort:
  - 31037
  - 30015
  - 30480
  - 31728
  - 30520
  - 31273
  - 30932
  - 32268
appName:
  - config-server
  - discovery-server
  - customers-service
  - visits-service
  - vets-service
  - api-gateway
  - tracing-server
  - admin-server
cantReplicas:
  - 1
  - 2
  - 1
  - 2
  - 1
  - 2
  - 1
  - 1