namespace: default
image:
  - name: app-graphql
    portExpose: 3000
  - name: app-introduccion
    portExpose: 3000
nodePort:
  - 31932
  - 31824
appName:
  - app-graphql
  - app-introduccion
cantReplicas:
  - 1
  - 2