namespace: default
image:
  - name: mimoqdocker-graphql
    portExpose: 3000
  - name: mimoqintroduccion-docker
    portExpose: 3000
nodePort:
  - 32614
  - 31505
appName:
  - mimoqdocker-graphql
  - mimoqintroduccion-docker
cantReplicas:
  - 2
  - 2