namespace: default
image:
  - name: app-graphql
    portExpose: 3000
  - name: app-introduccion
    portExpose: 3000
nodePort:
  - 31042
  - 30780
appName:
  - app-graphql
  - app-introduccion
cantReplicas:
  - 1
  - 2
containersPods: 2
minReplicas: 1
maxReplicas: 5
targetCPUUtilizationPercentage: 80
